name: Nightly Tests

on:
  schedule:
    - cron: "0 0 * * *"
  repository_dispatch:
    types: ["nightly-test"]
  push:
    branches:
      - nightly-test

env:
  RUST_TEST_THREADS: 1

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Install musl-tools
        run: "sudo apt-get install musl-tools"
      - uses: actions-rs/toolchain@v1
        with:
          profile: minimal
          toolchain: 1.53.0
          target: x86_64-unknown-linux-musl
          default: true
      - uses: Swatinem/rust-cache@v1
      - uses: actions-rs/cargo@v1
        with:
          command: test
          args: |
            --target=x86_64-unknown-linux-musl
            --test=github-nightly
            --features=github_nightly
            --no-run
      - name: Extract test executable
        run: |
          EXEC=$(ls -t target/x86_64-unknown-linux-musl/debug/deps/ | grep ^github_nightly | grep -v '\..' | head -n 1)
          mv target/x86_64-unknown-linux-musl/debug/deps/$EXEC target/x86_64-unknown-linux-musl/debug/github_nightly
      - uses: actions/upload-artifact@v2
        with:
          name: nightly-exec
          path: |
            target/x86_64-unknown-linux-musl/debug/edgedb
            target/x86_64-unknown-linux-musl/debug/github_nightly

  nightly-test:
    runs-on: ubuntu-latest
    needs: build
    timeout-minutes: 300
    strategy:
      fail-fast: false
      max-parallel: 4
      matrix:
        test_suite:
        - compat
        - install
        - upgrade
        - project
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: nightly-exec
      - name: Docker Permissions
        run: sudo chmod a+rw /var/run/docker.sock
      - name: Run Tests
        run: |
          chmod +x github_nightly edgedb
          EDGEDB_TEST_BIN_EXE="$(pwd)/edgedb" ./github_nightly ${{ matrix.test_suite }}::
        shell: bash
